<script lang="ts">
  import "@scottish-government/design-system/dist/css/design-system.css";
  import "@scottish-government/design-system/dist/scripts/design-system.js";
  import "@fortawesome/fontawesome-free/css/all.min.css";
  import { onMount } from "svelte";
  import { BackLink } from "../common";
  // This is generated by `npm run generate-manual`
  import Contents from "../manual/Contents.svelte";

  onMount(async () => {
    // @ts-expect-error This really exists for the SG design system, but TS doesn't know about it
    window.DS.initAll();
  });
</script>

<h1>Network Planning Workspace: User guide</h1>

<BackLink on:click={() => (window.location.href = "./")}>Back to NPW</BackLink>

<Contents />
