<script lang="ts">
  import "@scottish-government/design-system/dist/css/design-system.css";
  import "@scottish-government/design-system/dist/scripts/design-system.js";
  import "@fortawesome/fontawesome-free/css/all.min.css";
  import { onMount } from "svelte";
  import Toc from "svelte-toc";
  import favicon from "../../assets/favicon.ico?url";
  import { BackLink } from "../common";
  // This is generated by `npm run generate-manual`
  import Contents from "../manual/Contents.svelte";

  onMount(async () => {
    // @ts-expect-error This really exists for the SG design system, but TS doesn't know about it
    window.DS.initAll();
  });
</script>

<svelte:head>
  <link rel="icon" type="image/x-icon" href={favicon} />
</svelte:head>

<div class="container">
  <div class="contents">
    <h1>Network Planning Workspace: User guide</h1>

    <BackLink on:click={() => (window.location.href = "./")}>
      Back to NPW
    </BackLink>

    <Contents />
  </div>
  <div class="toc">
    <Toc title="Table of Contents" />
  </div>
</div>

<style>
  .container {
    display: flex;
  }
  .contents {
    width: 80%;
    padding: 16px;
  }
  .toc {
    width: 20%;
  }
</style>
