name: Deploy web

on:
  push:
    branches: [main, demo, nptless_demo]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: web/package-lock.json

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0

      - name: Cache WASM build
        uses: actions/cache@v4
        with:
          path: backend/target
          key: cargo-${{ hashFiles('backend/Cargo.lock') }}

      - name: Build web app
        run: ./release/gh_build.sh

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web/deployme/
